---
# tasks file for roles/osp-instance-delete
  - name: Fetch Instance Info
    os_server_info:
      cloud: ospcloud
    register: result

  - name: Check Var
    debug:
      msg: " {{ result }}"
  #- name: Delete instances
   
